sonar.projectKey=gfpaiva_tech-challenge-blog-aulas-frontend
sonar.organization=gfpaiva-github

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Tech Challenge Blog Aulas Frontend
# sonar.projectVersion=1.0.1

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions from analysis (completely ignore these files)
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.stories.tsx,**/node_modules/**

# Exclusions from coverage report
# The user wants to report coverage only for src/common and src/features
sonar.coverage.exclusions=src/app/**, src/infra/**, src/**/*.test.ts, src/**/*.test.tsx, src/**/*.stories.tsx, **/*.d.ts, src/common/index.ts, src/features/index.ts

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
